base_path_local: /Users/federicofilippello/Projects/dmeyf2024/src/experimentosfede
bucketname: fililocobuket
costo_estimulo: 7000
d_columns:
- cprestamos_personales
- mprestamos_personales
dataset_file: datasets_competencia_02_polars_baja3_6m.csv
dataset_path_local: /Users/federicofilippello/Projects/dmeyf2024/src/experimentosfede/
db_path: db/
ganancia_acierto: 273000
gcloud_user: fililoco
local: true
mes_test: 202103
mes_test_prediccion: 202106
mes_train:
- 202102
modelos_path: modelos/
n_trials: 40
semillas:
- 181194
study_aditional: ''
study_data: only_baja_3
study_number: '0'
study_protocol: lgmb
study_timeframe: '2023'
study_type: exp_colab_baja_semillero_2n
