base_path_local: /Users/federicofilippello/Projects/dmeyf2024/kaggle2/
bucketname: fililocobuket
costo_estimulo: 7000
d_columns:
- cprestamos_personales
- mprestamos_personales
dataset_file: competencia_02_inflacion_variablesFE.csv
dataset_pred_file: competencia_02_inflacion_variablesFE.csv
dataset_path_local: /Users/federicofilippello/Projects/dmeyf2024/kaggle2/
db_path: db/
ganancia_acierto: 273000
gcloud_user: fililoco
local: true
mes_test: 202008
mes_test_prediccion: 202108
mes_train:
  - 201908
  - 202008
modelos_path: modelos/
n_trials: 150
semillas:
- 181199
study_aditional: ''
study_data: all
study_number: '2'
study_protocol: lgmb
study_timeframe: '2023'
study_type: competencia_02_lgmb_de_08_local_infla_var
semillero_count: 30
vm_name: z104
